{
 "title": "Immich",
 "tags": [
  "immich",
  "prometheus"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Photos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_server_photos" }
   ]
  },
  {
   "title": "Videos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_server_videos" }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_server_usage_photos_bytes + immich_server_usage_videos_bytes"
    }
   ]
  },
  {
   "title": "Photo Growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(immich_server_photos[1h])\n-\nlast_over_time(immich_server_photos[1h] offset 1d)",
     "legendFormat": "Daily"
    },
    {
     "expr": "last_over_time(immich_server_photos[1h])\n-\nlast_over_time(immich_server_photos[1h] offset 7d)",
     "legendFormat": "Weekly"
    },
    {
     "expr": "last_over_time(immich_server_photos[1h])\n-\nlast_over_time(immich_server_photos[1h] offset 30d)",
     "legendFormat": "Monthly"
    }
   ]
  },
  {
   "title": "Video Growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(immich_server_videos[1h])\n-\nlast_over_time(immich_server_videos[1h] offset 1d)",
     "legendFormat": "Daily"
    },
    {
     "expr": "last_over_time(immich_server_videos[1h])\n-\nlast_over_time(immich_server_videos[1h] offset 7d)",
     "legendFormat": "Weekly"
    },
    {
     "expr": "last_over_time(immich_server_videos[1h])\n-\nlast_over_time(immich_server_videos[1h] offset 30d)",
     "legendFormat": "Monthly"
    }
   ]
  },
  {
   "title": "Storage Growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(immich_server_usage_bytes[1h])\n-\nlast_over_time(immich_server_usage_bytes[1h] offset 1d)",
     "legendFormat": "Daily"
    },
    {
     "expr": "last_over_time(immich_server_usage_bytes[1h])\n-\nlast_over_time(immich_server_usage_bytes[1h] offset 7d)",
     "legendFormat": "Weekly"
    },
    {
     "expr": "last_over_time(immich_server_usage_bytes[1h])\n-\nlast_over_time(immich_server_usage_bytes[1h] offset 30)",
     "legendFormat": "Monthly"
    }
   ]
  },
  {
   "title": "Photos and Videos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "immich_server_photos", "legendFormat": "Photos" },
    { "expr": "immich_server_videos", "legendFormat": "Videos" }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "immich_server_usage_bytes", "legendFormat": "Total usage" },
    {
     "expr": "immich_server_usage_photos_bytes",
     "legendFormat": "Photo usage"
    },
    {
     "expr": "immich_server_usage_videos_bytes",
     "legendFormat": "Video usage"
    }
   ]
  },
  {
   "title": "Photos by User",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(immich_user_photos)", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Videos by User",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(immich_user_videos)", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Storage Usage by User",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(immich_user_usage_bytes)",
     "legendFormat": "{{user_name}}"
    }
   ]
  }
 ]
}